debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.ssafy.common: debug
    org.springframework.web.service: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commonPJT
    useSSL: false
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
